---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: knative-operator
  namespace: flux-system
spec:
  interval: 24h
  url: https://knative.github.io/operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative-operator
  namespace: knative-operator
spec:
  interval: 24h
  releaseName: knative-operator
  targetNamespace: knative-operator
  chart:
    spec:
      chart: knative-operator
      sourceRef:
        kind: HelmRepository
        name: knative-operator
        namespace: flux-system
  install:
    createNamespace: false
  timeout: 30m
  values: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    domain:
      config-domain: |
        cluster.local: ""
    features:
      kubernetes.podspec-nodeselector: "enabled"
      kubernetes.podspec-tolerations: "enabled"
