---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: knative-operator
  namespace: flux-system
spec:
  interval: 24h
  url: https://knative.github.io/operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative-operator
  namespace: knative-operator
spec:
  interval: 24h
  releaseName: knative-operator
  targetNamespace: knative-operator
  chart:
    spec:
      chart: knative-operator
      sourceRef:
        kind: HelmRepository
        name: knative-operator
        namespace: flux-system
  install:
    createNamespace: false
  timeout: 30m
  values: {}
  test:
    enable: false
  rollback:
    cleanupOnFail: true
  upgrade:
    cleanupOnFail: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: knative-operator
            patch: |
              - op: replace
                path: /spec/template/spec/containers/0/readinessProbe
                value:
                  httpGet:
                    path: /readyz
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  successThreshold: 1
                  failureThreshold: 3
