---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kserve-oci
  namespace: flux-system
spec:
  type: oci
  interval: 24h
  url: oci://ghcr.io/kserve/charts
---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve-crd
  namespace: kserve
spec:
  interval: 24h
  releaseName: kserve-crd
  targetNamespace: kserve
  chart:
    spec:
      chart: kserve-crd
      version: v0.15.0
      sourceRef:
        kind: HelmRepository
        name: kserve-oci
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    createNamespace: false
  timeout: 30m
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve
  namespace: kserve
spec:
  interval: 24h
  releaseName: kserve
  targetNamespace: kserve
  chart:
    spec:
      chart: kserve
      version: v0.15.0
      sourceRef:
        kind: HelmRepository
        name: kserve-oci
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    createNamespace: false
  timeout: 30m
  dependsOn:
    - name: kserve-crd
  values:
    kserve:
      controller:
        deploymentMode: RawDeployment
        gateway:
          ingressGateway:
            enableGatewayApi: false
            kserveGateway: ""
      storage:
        image: kserve/storage-initializer
        tag: latest
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: "1"
